### ISSUE TITLE
Application List

### ISSUE THREAD

**Issue by emilkovacev** [makeopensource/Authenticator#6]
Applications need to be listed in the app, in order. Should be built for extensive customization.

## Task
Build an "app list" in React Native for the front page of the authenticator app. Each list item should contain the following:

**List Item**
- [ ] Application Name [Text]
- [ ] Application Icon [Image]
- [ ] Username for account [Text]
- [ ] TOTP password [Text]
